permalink: "/:year/:month/:day/:title.html"
name: "鸢飞无羁"
root: ""

author: "陈韵文"
atom-baseurl: "https://www.chenyunwen.cn"
disqus: "rose1988c"

navigations:
  - title: "Archive"
    class: "fa fa-list-ul"
    href: "/archive.html"
  - title: "Tags"
    class: "fa fa-tags"
    href: "/tags.html"
  - title: "About"
    class: "fa fa-user"
    href: "/about.html"
  - title: "MeBlog"
    class: "fa fa-film"
    href: "/blogs.html"
  - title: "Blogroll"
    class: "fa fa-link"
    href: "/links.html"
