permalink: "/:year/:month/:day/:title.html"
name: "鸢飞无羁"
subtitle: "子非鱼,只能以事论事"
root: ""

mytheme: "/themes/eston/"

# 分页
paginate: 5
paginate_path: "page:num"

# Plugins
gems:
  - jekyll-paginate

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

author: "陈韵文"
atom-baseurl: "http://www.chenyunwen.cn"
disqus: "rose1988c"
google: "UA-98154695-1"

navigations:
  - title: "Archive"
    class: "fa fa-list-ul"
    href: "/pages/archive.html"
  - title: "Tags"
    class: "fa fa-tags"
    href: "/pages/tags.html"
  - title: "About"
    class: "fa fa-user"
    href: "/pages/about.html"
  - title: "MeBlog"
    class: "fa fa-film"
    href: "/pages/blogs.html"
  - title: "Links"
    class: "fa fa-link"
    href: "/pages/links.html"
